version: '3.0'

networks:
    backend:
        driver: bridge

services:
    db:
        container_name: espotifai-db-service
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin # TODO: change it!
            - MONGO_INITDB_ROOT_PASSWORD=admin # TODO: change it!
        ports:
            - '27017:27017'
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
        networks:
            - backend

# TODO: create app service
