name: CI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install wget build-essential
          cd /tmp
          wget https://github.com/google/googletest/archive/refs/tags/release-1.10.0.tar.gz
          tar xvf release-1.10.0.tar.gz
          cd release-1.10.0
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
          cd tests
          mkdir build
          cmake ..
          ./espotifai_api_tests
